baseurl = "https://christospitsi.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Christos Pitsikas"
title = "  Christos Pitsikas"
# disqusshortname = ""
pluralizelisttitles = false
latestpostcount = 5

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Christos's Blog"
copyright = "Copyright © 2017 Christos Pitsikas, Powered by Hugo and Cocoa-Eh theme"
logofile = "img/logo.png"
faviconfile = "img/favicon.ico"
highlightjs = true
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
align_left = false
latestpostcount = 10
lang = "en"
github = "christospitsi"
email = "christos.pitsikas@gmail.com"
linkedin = "christos-pitsikas-0b817830"
googleAnalytics = "UA-109904395-1"
#twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
